---
#https://gitlab.eurecom.fr/oai/openairinterface5g/-/blob/develop/targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb.sa.band78.273prb.fhi72.4x4-benetel650.conf?ref_type=heads
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  du.conf: |
    Active_gNBs = ( "{{ .Values.config.duName }}");
    # Asn1_verbosity, choice in: none, info, annoying
    Asn1_verbosity = "none";
    gNBs =
    (
     {
        ////////// Identification parameters:
        gNB_ID    =  0xe12;
        gNB_name  =  "{{ .Values.config.duName }}";
        gNB_DU_ID = 0xe00;

        // Tracking area code, 0x0000 and 0xfffe are reserved values
        tracking_area_code  = {{ .Values.config.tac}} ;
        plmn_list = ({ mcc = {{ .Values.config.mcc}}; mnc = {{ .Values.config.mnc}}; mnc_length = 2; snssaiList = ({ sst = {{ .Values.config.sst}} }) });

        nr_cellid = 1;

        ////////// Physical parameters:
    
        pdsch_AntennaPorts_XP = 1;
        pusch_AntennaPorts    = 1;
        do_CSIRS              = 1;
        do_SRS                = 0;
        sib1_tda			        = 15;
    
        servingCellConfigCommon = (
        {
     #spCellConfigCommon
    
          physCellId                                                    = 0;
         # n_TimingAdvanceOffset                                         = 0;
    #  downlinkConfigCommon
        #frequencyInfoDL
          # center frequency = 3999.36 MHz
          # selected SSB frequency = 3999.36 MHz
          absoluteFrequencySSB                                          = 666624;
          dl_frequencyBand                                              = 77;
          # frequency point A = 3950.22 MHz
          dl_absoluteFrequencyPointA                                    = 665352;
          #scs-SpecificCarrierList
            dl_offstToCarrier                                           = 0;
    # subcarrierSpacing
    # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120
            dl_subcarrierSpacing                                        = 1;
            dl_carrierBandwidth                                         = 106;
         #initialDownlinkBWP
          #genericParameters
           initialDLBWPlocationAndBandwidth                             = 28875; #38.101-1 Table 5.3.2-1
           #
    # subcarrierSpacing
    # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120
            initialDLBWPsubcarrierSpacing                               = 1;
          #pdcch-ConfigCommon
            initialDLBWPcontrolResourceSetZero                          = 11;
            initialDLBWPsearchSpaceZero                                 = 0;
    
      #uplinkConfigCommon
         #frequencyInfoUL
          ul_frequencyBand                                              = 77;
          #scs-SpecificCarrierList
          ul_offstToCarrier                                             = 0;
    # subcarrierSpacing
    # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120
          ul_subcarrierSpacing                                          = 1;
          ul_carrierBandwidth                                           = 106;
          pMax                                                          = 23;
         #initialUplinkBWP
          #genericParameters
            initialULBWPlocationAndBandwidth                            = 28875;
    # subcarrierSpacing
    # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120
            initialULBWPsubcarrierSpacing                               = 1;
          #rach-ConfigCommon
            #rach-ConfigGeneric
              prach_ConfigurationIndex                                  = 159;
    #prach_msg1_FDM
    #0 = one, 1=two, 2=four, 3=eight
              prach_msg1_FDM                                            = 0;
              prach_msg1_FrequencyStart                                 = 0;
              zeroCorrelationZoneConfig                                 = 0;
              preambleReceivedTargetPower                               = -100;
    #preamblTransMax (0...10) = (3,4,5,6,7,8,10,20,50,100,200)
              preambleTransMax                                          = 7;
    #powerRampingStep
    # 0=dB0,1=dB2,2=dB4,3=dB6
            powerRampingStep                                            = 2;
    #ra_ReponseWindow
    #1,2,4,8,10,20,40,80
            ra_ResponseWindow                                           = 5;
    #ssb_perRACH_OccasionAndCB_PreamblesPerSSB_PR
    #1=oneeighth,2=onefourth,3=half,4=one,5=two,6=four,7=eight,8=sixteen
            ssb_perRACH_OccasionAndCB_PreamblesPerSSB_PR                = 4;
    #one (0..15) 4,8,12,16,...60,64
            ssb_perRACH_OccasionAndCB_PreamblesPerSSB                   = 15;
    #ra_ContentionResolutionTimer
    #(0..7) 8,16,24,32,40,48,56,64
            ra_ContentionResolutionTimer                                = 7;
            rsrp_ThresholdSSB                                           = 19;
    #prach-RootSequenceIndex_PR
    #1 = 839, 2 = 139
            prach_RootSequenceIndex_PR                                  = 2;
            prach_RootSequenceIndex                                     = 1;
            # SCS for msg1, can only be 15 for 30 kHz < 6 GHz, takes precendence over the one derived from prach-ConfigIndex
            #
            msg1_SubcarrierSpacing                                      = 1,
    # restrictedSetConfig
    # 0=unrestricted, 1=restricted type A, 2=restricted type B
            restrictedSetConfig                                         = 0,
    
    # this is the offset between the last PRACH preamble power and the Msg3 PUSCH, 2 times the field value in dB
            msg3_DeltaPreamble                                          = 2;
            p0_NominalWithGrant                                         = -100;
    
    # pucch-ConfigCommon setup :
    # pucchGroupHopping
    # 0 = neither, 1= group hopping, 2=sequence hopping
            pucchGroupHopping                                           = 0;
            hoppingId                                                   = 0;
            p0_nominal                                                  = -96;
    
          ssb_PositionsInBurst_Bitmap                                   = 0x1;
    
    # ssb_periodicityServingCell
    # 0 = ms5, 1=ms10, 2=ms20, 3=ms40, 4=ms80, 5=ms160, 6=spare2, 7=spare1
          ssb_periodicityServingCell                                    = 2;
    
    # dmrs_TypeA_position
    # 0 = pos2, 1 = pos3
          dmrs_TypeA_Position                                           = 0;
    
    # subcarrierSpacing
    # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120
          subcarrierSpacing                                             = 1;
    
    
      #tdd-UL-DL-ConfigurationCommon
    # subcarrierSpacing
    # 0=kHz15, 1=kHz30, 2=kHz60, 3=kHz120
          referenceSubcarrierSpacing                                    = 1;
          # pattern1
          # dl_UL_TransmissionPeriodicity
          # 0=ms0p5, 1=ms0p625, 2=ms1, 3=ms1p25, 4=ms2, 5=ms2p5, 6=ms5, 7=ms10
          dl_UL_TransmissionPeriodicity                                 = 6;
          nrofDownlinkSlots                                             = 7;
          nrofDownlinkSymbols                                           = 6;
          nrofUplinkSlots                                               = 2;
          nrofUplinkSymbols                                             = 4;
    
      ssPBCH_BlockPower                                                 = 0;
      }
      );
    
    
        # ------- SCTP definitions
        SCTP :
        {
            # Number of streams to use in input/output
            SCTP_INSTREAMS  = 2;
            SCTP_OUTSTREAMS = 2;
        };
      }
    );

    MACRLCs = (
    {
      num_cc                      = 1;
      tr_s_preference             = "local_L1";
      tr_n_preference             = "f1";
      local_n_if_name             = "{{ .Values.config.f1IfName}}";
      local_n_address             = "@F1_DU_IP_ADDRESS@";
      remote_n_address            = "@CU_IP_ADDRESS@";
      local_n_portc               = 500;
      local_n_portd               = {{ .Values.config.f1duPort}};
      remote_n_portc              = 501;
      remote_n_portd              = {{ .Values.config.f1cuPort}};
      pusch_TargetSNRx10          = 250;
      pucch_TargetSNRx10          = 250;
    }
    );


    L1s = (
    {
      num_cc = 1;
      tr_n_preference = "local_mac";
      prach_dtx_threshold = 130;
      pucch0_dtx_threshold = 80;
      ofdm_offset_divisor = 8;
      pusch_dtx_threshold = -100;
      tx_amp_backoff_dB = 0; # needs to match O-RU configuration
      L1_rx_thread_core = 8;
      L1_tx_thread_core = 10; # relevant after merge of l1_tx_thread
      phase_compensation = 0; # needs to match O-RU configuration      
    }
    );
    
    RUs = (
    {
      local_rf       = "no";
      nb_tx          = 1;
      nb_rx          = 1;
      att_tx         = 0;
      att_rx         = 0;
      bands          = [77];
      max_pdschReferenceSignalPower = -27;
      max_rxgain                    = 75;
      sf_extension                  = 0;
      eNB_instances  = [0];
      ru_thread_core = 9;
      sl_ahead       = 5;
      tr_preference  = "raw_if4p5"; # important: activate FHI7.2
      do_precoding   = 0; # needs to match O-RU configuration
    }
    );
    

    log_config :
    {
      global_log_level                      ="info";
      hw_log_level                          ="info";
      phy_log_level                         ="info";
      mac_log_level                         ="info";
      rlc_log_level                         ="info";
      pdcp_log_level                        ="info";
      rrc_log_level                         ="info";
      ngap_log_level                        ="info";
      f1ap_log_level                        ="info";
    };

    fhi_72 = {
      dpdk_devices = ("0000:01:00.0");
      system_core = 4;
      io_core = 5;
      worker_cores = (6);
      ru_addr = ("1c:a0:ef:87:68:b6");
      mtu = 9000;
      fh_config = ({
        T1a_cp_dl = (285, 470);
        T1a_cp_ul = (285, 429);
        T1a_up = (125, 350);
        Ta4 = (110, 180);
        ru_config = {
          iq_width = 9;
          iq_width_prach = 9;
        };
        prach_config = {
          eAxC_offset = 8;
        };
      });
    };
